"""Update Caregiver model with license_number field

Revision ID: 835e29399293
Revises: 
Create Date: 2024-03-07 14:26:02.688904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835e29399293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_number', sa.String(length=100), nullable=True))
        batch_op.drop_column('license')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('license_number')

    # ### end Alembic commands ###
