"""Add notes column to Appointment

Revision ID: c331e7053c03
Revises: 
Create Date: 2024-04-09 18:59:25.651849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c331e7053c03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('payment_status')
        batch_op.drop_column('care_requirements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_requirements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
